---
title: "Application exercises (AE)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---- 

Skip straight to a specific application exercise:

- [AE1](#ae1) Covid and sampling.
- [AE2](#ae2) 
- [AE3](#ae3)

---- 

### Where do I submit my application exercises?

This will be specified on a per-AE basis. You will submit some on Sakai, under Assignments. Some will specify that you should post on Piazza. Some may provide different instructions.

---

### AE1:

The following has been condensed from the "Lies, Darned Lies, and Statistics" episode of Sawbones (an entertaining medical history podcast):

Two doctors, who co-own a chain of urgent care clinics in Bakersfield, California, went viral late last month for suggesting the mortality rate of Covid-19 is similar to the flu. They argued that that there is no need to continue the shutdown, that we have done more damage than was necessary to the economy, and that we should immediately open everything back up.

These conclusions are based on the results of Covid-19 tests performed at their clinics. They say that 12% of Covid-19 tests came up positive, and from this they conclude that 12% of Californians are positive for Covid-19

From here, if you extrapolate to the United States population as a whole, you find that if 12% of the 330 million people in the US are Covid-19 positive, then  we can assume roughly 40 million are positive. From this, we can get the death rate as roughly 80 thousand divided by 40 million, which is 0.2% (only about twice that of the seasonal flu, which is estimated to be 0.1%).

1. Are individuals who get a Covid-19 test representative of the general population? Would we expect people getting tested to be more or less likely to have Covid-19 than a randomly sampled individual?
2. Are people in Bakersfield necessarily representative of the population of California? Of the US population? Why or why not?
3. Based on your answers to 1. and 2., should we assume that 12% of the US population is COVID-positive?
4. Would we expect the actual percent of people in the US who are COVID positive to be higher or lower than 12? Why?
5. How does your answer to 4. impact the assumed death rate made by the doctors? Is the death rate likely higher or lower?

Submit your responses to these questions **individually on Sakai**.

### AE2:


### AE3:

