---
title: "Detailed daily schedule"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following schedule will be stable once a week begins, but is subject to change up until midnight on Sunday at the start of the week. Please check frequently for updates. All live sessions will be available as a recording [under Resources in Sakai](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/tool/6db0f8ad-d49b-4034-8f6a-b2f47eae96bb?panel=Main).

<span style="color:blue">Live interactive and lab session times are shown in blue.</span>

<span style="color:red">Assignments due are shown in red.</span>

Skip straight to a specific week:

- [Week 0.5](#week-0.5), May 13-15.
- [Week 1](#week-1), May 18-22.
- [Week 2](#week-2), May 25-29.
- [Week 3](#week-3), June 1-5.
- [Week 4](#week-4), June 8-12.
- [Week 5](#week-5), June 15-19.
- [Week 6](#week-6), June 22-25.

---

# Week 0.5

---

This week, we begin Unit 1 (Introduction to Data). We'll get familiar with using the main learning resources and technologies needed for the class: the Coursera videos, the OpenIntro Statistics (OIS) textbook, R/Rstudio, and Piazza.

---

### Wednesday,  May 13

Topic: Data Collection + Observational studies and experiments (Start of Unit 1!)

To do:

- Read the [Learning Objectives for today and tomorrow](https://www.coursera.org/learn/probability-intro/supplement/rooeY/lesson-learning-objectives).
- View the [Introduction video](https://www.coursera.org/learn/probability-intro/lecture/UbGdZ/introduction).
- View the [Data Basics video](https://www.coursera.org/learn/probability-intro/lecture/Q0zu3/data-basics).
- View the [Observational Studies & Experiments video](https://www.coursera.org/learn/probability-intro/lecture/Qw8iF/observational-studies-experiments)
- Read OIS Chapter 1, Sections 1.1 and 1.2
- Begin work on questions from PS1
- Complete [Lab 0 (individual)](https://kelrenmor.github.io/STA101-002/labs/lab0/lab0) (not for credit)

<span style="color:blue">Interactive session (course intro, syllabus, and tools): 3-4:15 PM ET ([Kelly's Zoom room](https://duke.zoom.us/j/9271657735) and recorded)</span>

### Thursday,  May 14

Topic: Sampling

To do:

- Watch yesterday's course intro video (if you weren't able to attend live yesterday), saved [under the Resources tab on Sakai](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/tool/6db0f8ad-d49b-4034-8f6a-b2f47eae96bb?panel=Main)
- View the [Sampling and sources of bias video](https://www.coursera.org/learn/probability-intro/lecture/Y96uT/sampling-and-sources-of-bias)
- View the [Experimental design video](https://www.coursera.org/learn/probability-intro/lecture/Jyc3t/experimental-design)
- View the [Random Sample Assignment video](https://www.coursera.org/learn/probability-intro/lecture/N6gE8/spotlight-random-sample-assignment)
- Read OIS Chapter 1, Sections 1.3 and 1.4
- Continue work on questions from PS1
- Interact with Piazza discussion (to be posted this morning)
- Discuss Team expectations agreement (attachment in Sakai assignment), due tomorrow
- Begin working on [Lab 1 (teams)](https://kelrenmor.github.io/STA101-002/labs/lab1/lab1), due Monday 5/18

<span style="color:blue">Lab session: 4-5 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

### Friday,  May 15

Topic: Exploratory data analysis (EDA)

To do:

- Watch yesterday's Lab video (if you weren't able to attend live yesterday), saved under the [Resources tab on Sakai](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/tool/6db0f8ad-d49b-4034-8f6a-b2f47eae96bb?panel=Main)
- Read the [Learning Objectives for today](https://www.coursera.org/learn/probability-intro/supplement/Zsmno/lesson-learning-objectives)
- View the [Visualizing Numerical Data video](https://www.coursera.org/learn/probability-intro/lecture/9kRJf/visualizing-numerical-data)
- View the [Measures of Center video](https://www.coursera.org/learn/probability-intro/lecture/AM0o6/measures-of-center)
- View the [Measures of Spread video](https://www.coursera.org/learn/probability-intro/lecture/t9Wbk/measures-of-spread)
- View the [Robust Statistics video](https://www.coursera.org/learn/probability-intro/lecture/ssktR/robust-statistics)
- View the [Transforming Data video](https://www.coursera.org/learn/probability-intro/lecture/eQa2U/transforming-data)
- Read OIS Chapter 2, Section 2.1
- Continue work on questions from PS1
- Continue working on [Lab 1 (teams)](https://kelrenmor.github.io/STA101-002/labs/lab1/lab1), due Monday 5/18

<span style="color:blue">Group work session (drop in): Time 12:30-2 PM ET ([Kelly's Zoom room](https://duke.zoom.us/j/9271657735), any common questions to be posted on Piazza)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Team expectations agreement</span>

---

# Week 1

---

This week, we wrap up Unit 1 (Introduction to Data) on Monday, work through Unit 2 (Probability and distributions) Tuesday through Thursday, and begin Unit 3 (Foundations for inference) on Friday. We will also have a "data science in action" seminar from Dr. Josh Hewitt. Don't forget to pay attention to what is due each day; in all we will have two labs, two performance assesments, and two problem sets due this week. Note: as of 5/19 Dr. Hewitt has provided his seminar recording, which may be viewed under the Resources tab on Sakai. **The first reflection assignment (DSA1) may be found on Sakai in the 'Data Science in Action' folder under Resources-- it is called DSA1_Assignment_JoshHewitt.docx.**

---

### Monday,  May 18

Topic: More EDA + Introduction to statistical inference (End of Unit 1!)

To do: 

- Watch the Road Map to Week 1  video, saved under the Resources tab on Sakai
- Watch Friday's 'question summary' and 'sampling comment'  videos (if you weren't able to attend the group work session live), saved under the [Resources tab on Sakai](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/tool/6db0f8ad-d49b-4034-8f6a-b2f47eae96bb?panel=Main)
- Read the [Learning Objectives for today](https://www.coursera.org/learn/probability-intro/supplement/cLKTx/lesson-learning-objectives)
- View the [Exploring Categorical Variables video](https://www.coursera.org/learn/probability-intro/lecture/vEjt0/exploring-categorical-variables)
- View the [Introduction to Inference video](https://www.coursera.org/learn/probability-intro/lecture/e6IzY/introduction-to-inference)
- Read OIS Chapter 2, Sections 2.2 and 2.3
- Work on questions from PS1 (note PS1 is due tomorrow!)
- Wrap up [Lab 1 (teams)](https://kelrenmor.github.io/STA101-002/labs/lab1/lab1), due today
- Begin working on Lab 2 (teams), due Thursday

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 1</span>

### Tuesday,  May 19

Topic: Probability and conditional probability (Start of Unit 2!)

To do: 

- Take PA1 (performance assessment for Unit 1) on Sakai, due today
- View the Lab video from yesterday if you weren't able to attend live (saved under the Resources tab on Sakai)
- Read the [Learning Objectives for today](https://www.coursera.org/learn/probability-intro/supplement/zCmjJ/lesson-learning-objectives)
- View the [Introduction video](https://www.coursera.org/learn/probability-intro/lecture/07vL4/introduction)
- View the [Disjoint Events + General Addition Rule video](https://www.coursera.org/learn/probability-intro/lecture/qaYwc/disjoint-events-general-addition-rule)
- View the [Independence video](https://www.coursera.org/learn/probability-intro/lecture/D1m0l/independence)
- View the [Probability Examples video](https://www.coursera.org/learn/probability-intro/lecture/GqcO0/probability-examples)
- View the [Disjoint vs. Independent video](https://www.coursera.org/learn/probability-intro/lecture/PSXBC/spotlight-disjoint-vs-independent)
- Read OIS Chapter 3, Section 3.1 
- Finish up work on PS1 (due today), and begin work on questions from PS2
- Continue working on Lab 2 (teams), due Thursday

<span style="color:blue">Intro to Unit 2: Time 3-4pm ET ([Kelly's Zoom room](https://duke.zoom.us/j/9271657735))</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS1 + PA1 </span>

### Wednesday,  May 20

Topic: Bayes’ theorem and Bayesian inference

To do:

- View the Intro to Unit 2 video from yesterday if you weren't able to attend live (saved under the Resources tab on Sakai)
- Think about which of the first Data-science-in-action (DSA1) reflection options you'd like to complete (see DSA1_Assignment_JoshHewitt.docx on Sakai in the 'Data Science in Action' folder under Resources), and post to Piazza if you're seeking more teammates
- Read the [Learning Objectives for today](https://www.coursera.org/learn/probability-intro/supplement/uIBZA/lesson-learning-objectives)
- View the [Conditional Probability video](https://www.coursera.org/learn/probability-intro/lecture/fN6Kh/conditional-probability)
- View the [Probability Trees video](https://www.coursera.org/learn/probability-intro/lecture/QE3kX/probability-trees)
- View the [Bayesian Inference video](https://www.coursera.org/learn/probability-intro/lecture/qYbZQ/bayesian-inference)
- View the [Examples of Bayesian Inference video](https://www.coursera.org/learn/probability-intro/lecture/AWtbY/examples-of-bayesian-inference)
- Read OIS Chapter 3, Section 3.2
- Continue work on questions from PS2
- Continue working on Lab 2 (teams), due Thursday

<span style="color:blue">Go over PS1 + PA1: Time 11am-12pm ET ([Kelly's Zoom room](https://duke.zoom.us/j/9271657735))</span>

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>


### Thursday,  May 21

Topic: Normal + Binomial distribution  (End of Unit 2!)

To do:

- View the PS1 + PA1 video from yesterday if you weren't able to attend live (saved under the Resources tab on Sakai)
- Settle on which DSA1 reflection option you'd like to complete (see DSA1_Assignment_JoshHewitt.docx on Sakai in the 'Data Science in Action' folder under Resources), and your teammates (if not doing individual option)
- Read the [Learning Objectives for the normal distribution](https://www.coursera.org/learn/probability-intro/supplement/iElrX/lesson-learning-objectives)
- View the [Normal Distribution video](https://www.coursera.org/learn/probability-intro/lecture/M71Nv/normal-distribution)
- View the [Evaluating the Normal Distribution video](https://www.coursera.org/learn/probability-intro/lecture/snzoA/evaluating-the-normal-distribution)
- View the [Working with the Normal Distribution video](https://www.coursera.org/learn/probability-intro/lecture/mwnU6/working-with-the-normal-distribution)
- Read the [Learning Objectives for the binomial distribution](https://www.coursera.org/learn/probability-intro/supplement/vIhUM/lesson-learning-objectives)
- View the [Binomial Distribution video](https://www.coursera.org/learn/probability-intro/lecture/kJ07f/binomial-distribution)
- View the [Normal Approximation to Binomial video](https://www.coursera.org/learn/probability-intro/lecture/2sosk/normal-approximation-to-binomial)
- View the [Working with the Binomial Distribution video](https://www.coursera.org/learn/probability-intro/lecture/yef4b/working-with-the-binomial-distribution)
- Read OIS Chapter 4, Sections 4.1 and 4.3
- Continue work on questions from PS2, due tomorrow
- Finish working on Lab 2 (teams), due today

<span style="color:blue">Group work session (drop in): Time 5-6 PM ET ([Kelly's Zoom room](https://duke.zoom.us/j/9271657735), any common questions to be posted on Piazza)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 2</span>

### Friday,  May 22

Topic: Variability in estimates and CLT  (Start of Unit 3!)

To do: 

- Take PA2 (performance assessment for Unit 2) on Sakai, due today
- Agree with your team (if doing group option) on when you'll do DSA1 reflection either synchronously or asynchronously
- Read the [Learning Objectives for today](https://www.coursera.org/learn/inferential-statistics-intro/supplement/qRoWV/lesson-learning-objectives)
- View the [Introduction video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/EXe3o/introduction)
- View the [Sampling Variability and CLT video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/lkQnZ/sampling-variability-and-clt)
- View the [CLT (for the mean) examples video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/XhkI6/clt-for-the-mean-examples)
- Read OIS Chapter 5, Section 5.1
- Finish work on questions from PS2, due today, and begin work on questions from PS3

<span style="color:blue">NOTE: I added a video (as of 9am ET) discussing lab grading, the midterm, and Piazza. I will also be adding practice midterm exams to Sakai under Resources no later than 11:59 PM tonight, and will note this on Piazza when I do.</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS2 + PA2 </span>

---

# Week 2

---

This week, we have Monday off for Memorial day, Tuesday is a normal work day, Wednesday is a review for our first midterm on Thursday, and we wrap up the end of Unit 3 on Friday.

---

### Monday,  May 25

No class -- Memorial day.

No office hours or lab session.

Due today by 11:59 PM EDT: Nothing

### Tuesday,  May 26

Topic: Confidence intervals

To do: 

- Read the [Learning Objectives for today](https://www.coursera.org/learn/inferential-statistics-intro/supplement/TwF4J/lesson-learning-objectives)
- View the [Confidence Interval (for a mean) video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/DA30M/confidence-interval-for-a-mean)
- View the [Accuracy vs. Precision video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/QTajX/accuracy-vs-precision)
- View the [Required Sample Size for a ME video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/QPEXw/required-sample-size-for-me)
- View the [CI (for a mean) examples video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/txXVo/ci-for-the-mean-examples)
- Read OIS Chapter 5, Section 5.2
- Make sure you've completed and turned in DSA1 (due today)

<span style="color:blue">Q&A for practice exam questions (post to Piazza if you can’t come but want me to cover something): Time 5-7 PM ET ([Kelly's Zoom room](https://duke.zoom.us/j/9271657735) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: DSA1 </span>

### Wednesday,  May 27

Topic: Midterm 1 review

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Shifted office hours with Myra: 5-7 PM ET ([Myra's Zoom room](https://duke.zoom.us/j/9923268136))</span>

<span style="color:blue">Bonus office hours with Jason: 7-9 PM ET (Jason's Zoom room)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

### Thursday,  May 28

Topic: Midterm 1

Sakai issues? Let Kelly know and contact [OIT](https://oit.duke.edu/help).

To do: 

- Take Midterm 1

<span style="color:blue">Regularly scheduled office hours with Jason (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Midterm 1 + Lab 3 </span>

### Friday,  May 29

Topic: Hypothesis tests

To do: 

- Read the [Learning Objectives for today](https://www.coursera.org/learn/inferential-statistics-intro/supplement/98MG1/lesson-learning-objectives)
- View the [Another Introduction to Inference video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/GvyX6/another-introduction-to-inference)
- View the [Hypothesis Testing (for a mean) video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/nnn84/hypothesis-testing-for-a-mean)
- View the [HT (for the mean) examples video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/nKo0b/ht-for-the-mean-examples)
- Read OIS Chapter 5, Section 5.3

<span style="color:blue">No regularly scheduled office hours (but available on request -- email if you want to talk)</span>

---

# Week 3

---

This week, we have a **live Data Science in Action seminar** on Friday with Dr. David Gill from 1-2pm ET (will be recorded for those unable to attend live). He will be discussing his work on marine protected areas. We begin Unit 4 (Inference for categorical variables) on Monday and wrap up that unit Wednesday, then begin Unit 5 (Inference for numerical variables) on Thursday. In addition to "regular programming" from Coursera and OIS, this week I'll be providing more information about your final project so you can begin working on your proposal (due next Thursday). I'll also be going over Midterm 1 problems/scores, addressing some nuances from Unit 3 (diving deeper into the idea of a confidence interval), and providing additional content about reporting and interpreting data/statistics.

---

### Monday, June 1

Topic: Inference for a single proportion

To do: 

- Note I left comments on your DSA1 submissions - go to the Assessment on Sakai to see. Will post when Josh responds to questions!
- Watch the Midterm 1 Common Issues video, saved [under the Resources tab on Sakai](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/tool/6db0f8ad-d49b-4034-8f6a-b2f47eae96bb?panel=Main)
- Read the [Learning Objectives for today and tomorrow](https://www.coursera.org/learn/inferential-statistics-intro/supplement/AphlU/lesson-learning-objectives)
- View the [Introduction to Inference for Categorical Variables video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/ruAZK/introduction)
- View the [Sampling Variability and CLT for Proportions video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/oJxbr/sampling-variability-and-clt-for-proportions)
- View the [Confidence Interval for a Proportion video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/nK388/confidence-interval-for-a-proportion)
- View the [Hypothesis Test for a Proportion video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/VAo5K/hypothesis-test-for-a-proportion)
- Read OIS Chapter 6, Section 6.1
- Work on PS4 problems from section 6.1
- Wrap up and submit PS3 + Lab 4 (due today)!
- Don't forget to take PA3 (due today) and reflect on your understanding of Unit 3!
- Work on Midterm 1 corrections (optional) -- template on Sakai under Resources.

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS3 + PA3 + Lab 4 </span>

### Tuesday, June 2

Topic: Inference for comparing two proportions

To do: 

- Review the [Learning Objectives for today and yesterday](https://www.coursera.org/learn/inferential-statistics-intro/supplement/AphlU/lesson-learning-objectives)
- View the [Estimating the Difference Between Two Proportions video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/kI4Ma/estimating-the-difference-between-two-proportions)
- View the [Hypothesis Test for Comparing Two Proportions video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/vMH7n/hypothesis-test-for-comparing-two-proportions)
- Read OIS Chapter 6, Section 6.2
- Work on PS4 problems from section 6.2
- Work on Midterm 1 corrections (optional).

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: MT1 Corrections </span>

### Wednesday, June 3

Topic: Chi-square testing

To do: 

- Read the [Learning Objectives for today](https://www.coursera.org/learn/inferential-statistics-intro/supplement/bd1oR/lesson-learning-objectives)
- View the [Small Sample Proportions video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/B7mb4/small-sample-proportions)
- View the [Examples video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/w7VQF/examples)
- View the [Comparing Two Small Sample Proportions video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/rUhQw/comparing-two-small-sample-proportions)
- View the [Chi-Square GOF Test video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/OO6iS/chi-square-gof-test)
- View the [Chi-Square Independence Test video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/LEIm3/the-chi-square-independence-test)
- Read OIS Chapter 6, Section 6.3
- Work on PS4 problems from section 6.3 and 'all section' problems
- Wrap up and turn in Lab 5 (due today)

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 5 </span>

### Thursday, June 4

Topic: Inference using the t-distribution

To do: 

- Read the [Learning Objectives for today and tomorrow](https://www.coursera.org/learn/inferential-statistics-intro/supplement/KxvWg/lesson-learning-objectives)
- View the [Introduction to Inference for Numerical Variables video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/xtUR0/introduction)
- View the [t-distribution video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/FlRrd/t-distribution)
- View the [Inference for a mean video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/qs7Ml/inference-for-a-mean)
- Read OIS Chapter 7, Sections 7.1 and 7.2
- Work on PS5 problems from sections 7.1 and 7.2
- Wrap up and submit PS4 (due today)!
- Don't forget to take PA4 (due today) and reflect on your understanding of Unit 4!

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS4 + PA4 </span>

### Friday, June 5

Topic: Inference for comparing two means + Power

To do: 

- Review the [Learning Objectives for today and yesterday](https://www.coursera.org/learn/inferential-statistics-intro/supplement/KxvWg/lesson-learning-objectives)
- View the [Inference for comparing two independent means video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/wkwlZ/inference-for-comparing-two-independent-means)
- View the [Inference for comparing two paired means video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/k5zhM/inference-for-comparing-two-paired-means)
- View the [Power video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/kdnQf/power)
- Read OIS Chapter 7, Sections 7.3 and 7.4
- Work on PS5 problems from sections 7.3 and 7.4

<span style="color:blue">Live data science in action seminar with [David Gill](https://nicholas.duke.edu/people/faculty/gill): Time 1-2pm ET</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

---

# Week 4

---

### Monday, June 8

Topic: ANOVA

To do: 

- Read the [Learning Objectives for today and tomorrow](https://www.coursera.org/learn/inferential-statistics-intro/supplement/ctr7d/lesson-learning-objectives)
- View the [Comparing more than two means video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/TI3DD/comparing-more-than-two-means)
- View the [ANOVA video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/KoTvZ/anova)
- View the [Conditions for ANOVA video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/hSgp3/conditions-for-anova)
- View the [Multiple comparisons video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/6wfP3/multiple-comparisons)
- Read OIS Chapter 7, Section 7.5
- Work on PS5 problems from sections 7.5 and rest of chapter

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

### Tuesday, June 9

Topic: Bootstrapping

To do: 

- View the [Bootstrapping video](https://www.coursera.org/learn/inferential-statistics-intro/lecture/u3k1n/bootstrapping)
- Wrap up Lab 6 (due today)
- Work on project proposal (due Thursday)
- Work on PS5 problems (due Friday)

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 6 </span>

### Wednesday, June 10

Topic: Midterm 2 review

To do: 

- Review for midterm 2
- Work on project proposal (due tomorrow)

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

### Thursday, June 11

Topic: Midterm 2

To do: 

- Take Midterm 2
- Wrap up and submit project proposal

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Midterm 2 + Project proposal</span>

### Friday, June 12

Topic: Introduction to regression

To do: 

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS5 + PA5 </span>

---

# Week 5

---

### Monday, June 15

Topic: Outliers and Inference for SLR

To do: 

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 7 </span>

### Tuesday, June 16

Topic: Introduction to multiple linear regression

To do: 

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS6 + PA6 </span>

### Wednesday, June 17

Topic: Model selection and diagnostics for MLR

To do: 

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

### Thursday, June 18

Topic: Transformation and case studies

To do: 

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 8</span>

### Friday, June 19

Topic: Review and project work

To do: 

- Review for final
- Work on Lab 9
- Work on individual project
- Wrap up and submit PS7 
- Take PA7

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: PS7 + PA7</span>

---

# Week 6

---

### Monday, June 22

Topic: Review and project work

To do: 

- Review for final
- Wrap up and submit Lab 9
- Wrap up and submit individual project

<span style="color:blue">Lab session: 2-3:15 PM ET ([Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) and recorded)</span>

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Lab 9 + Project</span>

### Tuesday, June 23

Topic: View and respond to assigned project presentations

To do: 

- Review for final
- Project reflection

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

<span style="color:red">Due today by 11:59 PM EDT: Project reflection</span>

### Wednesday, June 24

Topic: Reading day

To do: Prepare for final exam (tomorrow!)

<span style="color:blue">Regularly scheduled office hours (see main page)</span>

### Thursday, June 25

Topic: Final exam

To do: Take final exam and celebrate!

<span style="color:red">Due today by 11:59 PM EDT: Final exam</span>
