---
title: "STA 101-002: Data Analysis and Statistical Inference (Summer 1 2020)"
output: 
  html_document:
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "STA 101-002: Data Analysis and Statistical Inference (Summer 1 2020)"
description: ". Prerequisite: None."
markup: "mmark"
---

# Welcome to STA101-002!

### About the Course

STA 101-002 introduces students to the discipline of statistics as a science of understanding and analyzing data. Throughout the semester, students will learn how to effectively make use of data in the face of uncertainty: How to collect data, how to analyze data, and how to use data to make inferences and conclusions about real world phenomena. The course emphasizes examples from marine science, environmental science, conservation and energy issues. This section is ordinarily taught in person at Duke's Marine Lab campus, but will be taught asynchronously online for Summer Term 1 2020.

Work ethic, the ability to self-motivate, flexibility, logical thinking, professionalism, and communication skills are all strong predictors of success in STA 101-002 (as well as in the working world). Don't worry if you haven't mastered all of these -- we'll work on them in class!

### Class Meetings

<font color="#6CA0DC"><i class="fas fa-university fa-lg"></i></font> &nbsp; Zoom (asynchronous)

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; MTWThF (office hours with instructor or TAs, live group work sessions, and seminars -- which will be recorded)

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; MW 2-3:15pm lab sessions (intro will be recorded, followed by live work session) in [Ezinne's Zoom room](https://duke.zoom.us/j/2914105963)

See below for current week's live session times (note that these times are **in addition to** office hours, which are shown in the next section). Recordings will be placed [under resources on Sakai](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/tool/6db0f8ad-d49b-4034-8f6a-b2f47eae96bb?panel=Main) for those who cannot attend live, arranged by date. 

| Day | Time | Team member | Topic | Location |
| ---   | ---   | ---   | ----  | ---- |
| Monday,  June 1 | 2-3:15pm | Ezinne | Lab session | [Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) |
| Tuesday,  June 2 | 3-5pm | Dr. Moran | Drop in time to talk about Midterm 1 | [Kelly's Zoom room](https://duke.zoom.us/j/9271657735) |
| Wednesday,  June 3 | 2-3:15pm | Ezinne | Lab session | [Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) |
| Friday,  June 5 | 1-2pm | Dr. David Gill | Data Science in Action seminar | [Kelly's Zoom room](https://duke.zoom.us/j/9271657735) |

### Teaching team and office hours 

Additional times available on request. All times are in Eastern time zone. Note: office hours may vary. Revisions to office hours will be noted via e-mail and on the webpage. 

<span style="color:red">Additional office hours available on request (just send an email!)</span>

| Team member | Email | Office hours | Location |
| -- | -- | ---- | -- |
| [Dr. Kelly Moran](https://stat.duke.edu/people/kelly-moran) | kelly.r.moran@duke.edu | M 10-11am, T 2-3pm, W 10-11am, Th 6-7pm | [Kelly's Zoom room](https://duke.zoom.us/j/9271657735) |
| [TA Ezinne Nwankwo](https://stat.duke.edu/people/ezinne-nwankwo) | ezinne.nwankwo@duke.edu | M 3:15-5pm, W 3:15-5pm | [Ezinne's Zoom room](https://duke.zoom.us/j/2914105963) |
| TA Jason McEachin | marcus.mceachin@duke.edu | T 7-9pm, Th 7-9pm | [Jason's Zoom room](https://sakai.duke.edu/portal/site/eaca1fc1-5920-4d0a-b7a6-6f33b35d298e/page/6f2b8b5d-66df-4833-bd08-787e2aa06c11) |
| TA Myra Cai | myra.cai@duke.edu | F 4-6pm | [Myra's Zoom room](https://duke.zoom.us/j/9923268136) |

### Teams

See the [Group dynamics](https://kelrenmor.github.io/STA101-002/grouppolicies) page for team assignments. Let me know if you or a team member intends to drop the class so we can restructure your team.

### Materials

The course textbook is [OpenIntro Statistics 4th Ed](https://leanpub.com/openintro-statistics) - Diez, Barr, Cetinkaya-Rundel (2019). It is free online, or can be purchased from Amazon at cost of printing. Additional texts and readings will be assigned as needed. We will support computation in R and RStudio. You will be allowed to use a calculator in class; a simple calculator that can take square roots will be sufficient.

### Data science in action speakers by week

- May 13-15: None (first week)
- May 18-22: [Joshua Hewitt](https://jmhewitt.github.io/) (asynchronous and posted on Sakai)
- May 25-29: None (last week delayed, so extra time)
- June 1-5: [David Gill](https://nicholas.duke.edu/people/faculty/gill) (there will be a synchronous session at 1pm on Friday, June 5)
- June 8-12: [Kersey Sturdivant](https://nicholas.duke.edu/people/faculty/sturdivant)
- June 15-19: [Kate Hoffman](https://nicholas.duke.edu/people/faculty/hoffman)
- June 22-25: None (last week)

### Schedule at a glance

STA 101-002 has a tight turnaround on due dates to ensure no one falls behind; in return, the instruction team will return graded assignments no later than 48 hours after submission. Use the schedule below for a quick guide to topics and due dates. For a more complete schedule providing specific material for daily readings/viewings, see the [Detailed schedule](https://kelrenmor.github.io/STA101-002/daily_schedule) tab.

Note: this schedule is approximate and is likely to be modified as the course progresses. Some sessions may be swapped due to course timing. Please check frequently for updates. Assignments are due by 11:59 PM EDT unless otherwise specified. 

|Date |Topic |Due |Special notes |
| ----------- | --------------------------- | --------------- | --------------- |
| Wednesday,  May 13 | Data Collection + Observational studies and experiments | | First day of class! Begin Unit 1: Introduction to Data. |
| Thursday,  May 14| Sampling |  | |
| Friday,  May 15| Exploratory data analysis | Team agreement | |
| ----------- | --------------------------- | --------------- | Enjoy your weekend! |
| Monday,  May 18| More EDA + Introduction to statistical inference | Lab 1 | |
| Tuesday,  May 19| Probability and conditional probability | PS1 + PA1 | Begin Unit 2: Probability and distributions |
| Wednesday,  May 20| Bayes' theorem and Bayesian inference | | |
| Thursday,  May 21| Normal + Binomial distribution | Lab 2 |  |
| Friday,  May 22| Variability in estimates and CLT | PS2 + PA2 | Begin Unit 3: Foundations for inference |
| ----------- | --------------------------- | --------------- | Enjoy your weekend! |
| Monday,  May 25|  | | No class Memorial Day |
| Tuesday,  May 26| Confidence intervals | DSA1 | |
| Wednesday,  May 27| Midterm 1 review | | |
| Thursday,  May 28| Midterm 1 | Lab 3 | |
| Friday,  May 29| Hypothesis tests | | |
| ----------- | --------------------------- | --------------- | Enjoy your weekend! |
| Monday,  June 1| Inference for a single proportion | PS3 + PA3 | Begin Unit 4: Inference for categorical variables |
| Tuesday,  June 2| Inference for comparing two proportions | MT1 Corrections + Lab 4 | |
| Wednesday,  June 3| Chi-square testing | | |
| Thursday,  June 4| Inference using the t-distribution | PS4 + PA4 | Begin Unit 5: Inference for numerical variables |
| Friday,  June 5| Inference for comparing two means + Power | Lab 5 | Data-science-in-action with David Gill |
| ----------- | --------------------------- | --------------- | Enjoy your weekend! |
| Monday,  June 8| ANOVA | | |
| Tuesday,  June 9| Bootstrapping | Lab 6 | |
| Wednesday,  June 10| Midterm 2 review | | |
| Thursday,  June 11| Midterm 2 | Project proposal |  |
| Friday,  June 12| Introduction to regression | PS5 + PA5 | Begin Unit 6: Introduction to linear regression |
| ----------- | --------------------------- | --------------- | Enjoy your weekend! |
| Monday,  June 15| Outliers and Inference for SLR | Lab 7 | |
| Tuesday,  June 16| Introduction to multiple linear regression | PS6 + PA6 | Begin Unit 7: Multiple linear regression |
| Wednesday,  June 17| Model selection and diagnostics for MLR |  | |
| Thursday,  June 18| Transformation and case studies | Lab 8 | |
| Friday,  June 19| Review and project work | PS7 + PA7 | |
| ----------- | --------------------------- | --------------- | Enjoy your weekend! |
| Monday,  June 22| Review and project work | Lab 9 + Project | |
| Tuesday,  June 23|  View and respond to project presentations | Project reflection |  |
| Wednesday,  June 24| Reading day |  | |
| Thursday,  June 25| Final exam |  |  Last day of class! |

