---
title: "Labs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

--- 

### Where do I submit my labs?

You will submit your labs on Sakai, under Assignments.

### How do I submit my labs?

When you are done with a lab, export **both** the Rmd and the HTML (or PDF-- follow lab instruction for each lab) files you created, and upload them to Sakai under the appropriate assignment. To export, check the box next to the Rmd and the HTML (or PDF) files for the lab, click on More, and then Export. This will download the files (likely to your Desktop or your Downloads folder, depending on your operating system and configurations). You can then upload these files to Sakai. Step-by-step instructions for exporting/submission can be found on the [course FAQ](https://kelrenmor.github.io/STA101-002/faq/#r5). When labs are to be done in teams, only one submission per team is required.

### If a lab is individual, can I still work with other people?

Yes, we encourage you to work with and talk to your fellow students! However, you will have to complete and turn in your own assignment. See the [Academic integrity](https://kelrenmor.github.io/STA101-002/syllabus/#academic-integrity) section of the syllabus.

### What do I do if I get stuck?

Attend a live lab session or view the lab session recording, reach out on Piazza, come to office hours, ask your fellow students. Don't spend forever banging your head against a wall -- labs should feel interesting or challenging, but not impossible or demotivating.

### How are labs graded?

See the [Group dynamics](https://kelrenmor.github.io/STA101-002/grouppolicies) page for how team lab grading works.

The following will lead to point deductions on labs:

- Missing interpretation or content
  - Exercise asks for a plot/table, but no plot/table included
  - Exercise asks for your observations, what you see, for you to reflect on something specific, etc. and you do not include this
  - Include some detail, but missing key part(s) 
- Missing code
  - Do not use code when should have (e.g., if you go through a data set by hand to find the minimum rather than using code)
  - Used code, but did not include it in the output (e.g., if you did something in the console but didn't add a code chunk to show your work)
- Correctness
  - Your plot/table contains the wrong information, or a different type of information/data than asked for
  - You make incorrect conclusions
- Formatting
  - Not taking out comments like "enter code here" from the template
  - Inappropriate text size, or formatting response text as header
  - Code not easily readable in one line
- Misc 
  - Random number seed set multiple times (i.e., use `set.seed` more than once)
  - Anything specific to a particular lab not covered here

---

### [Lab 0 (individual)](https://kelrenmor.github.io/STA101-002/labs/lab0/lab0)

### [Lab 1 (teams)](https://kelrenmor.github.io/STA101-002/labs/lab1/lab1)

### [Lab 2 (teams)](https://kelrenmor.github.io/STA101-002/labs/lab2/lab2)

### [Lab 3 (individual)](https://kelrenmor.github.io/STA101-002/labs/lab3/lab3)

### Lab 4

### Lab 5

### Lab 6

### Lab 7

### Lab 8

### Lab 9

