---
title: "Problem sets (PS)"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---- 

Graded problems are available as html links below, or as Word templates on Sakai under the resources tab. They are often modified from questions in OpenIntro Statistics, 4th Edition.

Practice problems are from OpenIntro Statistics, 4th Edition. 

You only need to turn in the answers to the graded problems. You can work with your classmates on the homework but you must turn in your own work. The answers to questions must be in your own words.

You must show **all** work to get credit. 

--- 

### Where do I submit my problem sets?

You will submit your problem sets on Gradescope.

### How do I submit my problem sets?

First, log into Gradescope using your Duke credentials [here](https://www.gradescope.com/saml). We **strongly** recommend working in a word processor of your choice, saving your work as PDF, and submitting that. You may also handwrite and take a photo of your work, but if the grader cannot read your writing (due to handwriting or photo quality) you will not receive points. See [Gradescope help page](https://www.gradescope.com/help#help-center-section-student-workflow) for common questions related to GradeScope.

### Do I need to turn in practice problems?

You do not need to turn in your answers for the practice problems. In fact, brief solutions  to these problems are provided at the end of the book. However you are strongly encouraged to work through them to make sure that you grasp the material we have covered so far. You are also welcome to ask questions about them during office hours.

### What do I do if I think a question is wrong?

Textbook errata: If you read something that doesn't make sense first check to see if it's been corrected already. If not, send me an email about it so that I can confirm whether it's a typo or not, and if it is, it'll be added to the list. A list of known errata can be found [here](https://docs.google.com/spreadsheets/u/1/d/1qifH8VDF0p3xVaFrnOAdmX5MLVODAw6JqeAS8OinUs4/htmlview).

If you think one of the non-textbook questions has an error, post to Piazza or email me directly.

---

### PS1:

Graded questions: See [assignment file](https://kelrenmor.github.io/STA101-002/problem_sets/PS_1), or download Word template on Sakai under the Resources tab. Submit to Gradescope.

Practice questions: 

* Chapter 1: 1.1, 1.3, 1.15, 1.17, 1.19, 1.21, 1.27, 1.29, 1.39
* Chapter 2: 2.3, 2.7, 2.11, 2.15, 2.19, 2.21, 2.23, 2.25, 2.27

### PS2:

Graded questions: See [assignment file](https://kelrenmor.github.io/STA101-002/problem_sets/PS_2), or download Word template on Sakai under the Resources tab. Submit to Gradescope.

Practice questions: 

* Chapter 3: 3.1, 3.3, 3.5, 3.7, 3.13, 3.17, 3.19, 3.39, 3.41
* Chapter 4: 4.3, 4.5, 4.9, 4.17, 4.19, 4.23, 4.37, 4.39

### PS3:

Graded questions: TBA

Practice questions: 5.1, 5.3, 5.5, 5.9, 5.11, 5.15, 5.17, 5.21, 5.23, 5.25, 5.27, 5.29, 5.31, 5.33, 5.35, 5.37

### PS 4:

Graded questions: TBA

Practice questions: TBA

### PS 5:

Graded questions: TBA

Practice questions: TBA

### PS 6:

Graded questions: TBA

Practice questions: TBA

### PS 7:

Graded questions: TBA

Practice questions: TBA

  