---
title: "Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---- 

The project objective is to give you independent applied research experience using real data and statistical methods. For a parameter of interest to you, you will describe the relevant data, conduct an analysis, and summarize your findings in a written, fully reproducible, data analysis report. You will also upload a short video presentation in which you share your work with your peers. Students will view and engage with a subset of their peers’ projects, and respond to questions from those who viewed their presentation in the "project reflections" component of the assignment.

* [Project proposal](https://kelrenmor.github.io/STA101-002/project_files/project_st1_statement) (extended due date Saturday, June 13): 2/10 of overall project grade
* [Project write-up/presentation](https://kelrenmor.github.io/STA101-002/project_files/project_st2_statement) (due Monday, June 22): 7/10 of overall project grade
* Project reflections (due Tuesday, June 23): 1/10 of overall project grade

You must score at least 30% of the points on each of the three project related submissions in order to pass this class.

---- 

Two examples of a Proposal (i.e., Stage 1) submission scoring full points are available [here](https://kelrenmor.github.io/STA101-002/project_files/Stage1_example_2) and [here](https://kelrenmor.github.io/STA101-002/project_files/Stage1_example_1), and both the Rmd and html files are on Sakai under the Resources tab. Note that for the provided example proposal, the assignment required three questions in the proposal (you are only asked to come up with two for your assignments).

My (sketched out, not fully completed) example of how Stage 2 should look, along with some FAQs, is available [here](https://kelrenmor.github.io/STA101-002/project_files/Stage2_example).

Rubrics for the project write up and presentation are available on Sakai under Resources. An example of a final presentation (i.e., Stage 2) is also provided on Sakai.

---- 

## Recommended little-bit-a-day completion plan:

### For Stage 1

- Monday, June 8: Choose your data set and come up with two research questions
- Tuesday, June 9: Come up with hypotheses for your two research questions, and references
- Wednesday, June 10: Do EDA and discussion for Q1
- Thursday, June 11: Do EDA and discussion for Q2
- Friday, June 12: Wrap up and double check work

### For Stage 2

- Monday, June 15: Review feedback from project proposal and decide what question/variables to focus on for final project
- Tuesday, June 16: Write introduction section and work on analysis - EDA section (use proposal and comments received)
- Wednesday, June 17: Work on analysis - hypothesis test and full model sections
- Thursday, June 18: Work on analysis - model selection, assessing the performance, and making a prediction sections (see video from today on Sakai under Resources tab for talk through of example)
- Friday, June 19: **RENAME YOUR PROJECT RMD FILE** (e.g., sta101_prj.Rmd should be renamed, with your name instead of mine, Moran_Kelly_sta101_prj.Rmd). Work on conclusion, clean up other sections, begin presentation skeleton (see Sakai under Resources tab for presentation rubric, video describing expectations to be added to Resources tab by 5pm today)
- Weekend, June 20-21: Try to relax! (But work on slides for presentation if you want to get stuff done in advance of Monday)
- Monday, June 22: Clean and wrap up written component, make and record 8 minute presentation (see Sakai under Resources tab for presentation rubric), and submit the Rmd, html or pdf, and video on Sakai + **drop the video in the Duke box folder I shared with you** (see below) so your "reviewers" can access it

The groups/folders in which you should upload your **presentation video** are as follows: 

- [Folder for Group A](https://duke.box.com/s/5wcea496knys7vm7n2mfatfyx6hmb3is): accessible to Xavier, Juliana, Connor, Rachel H., and Zoe
- [Folder for Group B](https://duke.box.com/s/jf4hzjxhj8z4mcq5wi0su54v9th7rx7z): accessible to Joshua, Brooke, Skylar, Braden, and Jules
- [Folder for Group C](https://duke.box.com/s/n9aqduypjuhrdyyiw951jx4a2lrkvgmm): accessible to Rachel P., Olivia, Alexa, Cynthia, and Aaron
- [Folder for Group D](https://duke.box.com/s/zwr2q1q2o4dzh1y3y4x2l8uqruka59wr): accessible to Kylie, Paige, Kate, Alice, and Giselle
- [Folder for Group E](https://duke.box.com/s/xq4728wm8hsizdwy27orep9opuwbcb67): accessible to Maya, Rand, Ghalia, Zavera, and Elana

### For Stage 3

You have each been provided access to a Duke Box folder (see links above), in which you should have shared the video recording of your project presentation.

The assignment for reflection will be shown here soon.
