---
title: "Syllabus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---- 

## Class meeting information

This is an online, asynchronous introductory statistics course designed to develop practical skills in understanding and analyzing marine science, environmental, and energy data. Asynchronous means that there are no required class meetings; students may access materials, view lectures, and participate actively on Piazza within their own daily schedule. However, the course will include interactive seminars, group work sessions, virtual office hours, and lab sessions; these will be scheduled based on availability. Students are encouraged to come to live seminars and work sessions if they are able to, and recordings will be made available for those who are not. The content calendar and due dates are designed such that students will undergo shared consistent learning over the 6 week Summer 1 term, and students should expect there to be some kind of deadline or deliverable most weekdays.

## Course goals & objectives

This course introduces students to the discipline of statistics as a science of understanding and analyzing data. Throughout the semester, students will learn how to effectively make use of data in the face of uncertainty: how to collect data, how to analyze data, and how to use data to make inferences and conclusions about real world phenomena. Examples, labs, and project will emphasize marine science, environmental, and energy issues.

The course goals are as follows:

1. Recognize the importance of data collection, identify limitations in data collection methods, and determine how these limitations affect the scope of inference.
2. Use statistical software to explore data, summarize data numerically and visually, and to perform data analysis.
3. Apply estimation and testing methods to analyze single variables or the relationship between two variables in order to understand natural phenomena and make data-based decisions.
4. Model numerical response variables using explanatory variable(s).
5. Interpret results correctly, effectively, and in context in a way that laypeople can understand (i.e., without relying on statistical jargon).
6. Critique data-based claims and evaluate data-based decisions.
7. Complete a research project that focuses on statistical inference.

## Required materials

- Textbook: OpenIntro Statistics (4th Edition, 2019), by Diez, Çetinkaya-Rundel, and Barr. (ISBN: 1943450072).
    - The textbook is freely available online. You’re welcomed to read on screen or print it out. If you prefer a paperback version you can buy it at the cost of printing ($20) on Amazon. 
- Equipment / software: Computer + stable internet access + video/audio capability + latest version of Firefox, Chrome, or Safari installed on your operating system.
- Calculator (optional): You may use a calculator in this class. There is no restrictions on the type of calculator. A simple calculator that can take square roots should be sufficient.

----

### Diversity & inclusiveness

The Duke University Community Commitment states: "Because diversity is essential to fulfilling the university’s mission, Duke is committed to building an inclusive and diverse university community.  Every student, faculty, and staff member —whatever their race, gender, age, ethnicity, cultural heritage or nationality; religious or political beliefs; sexual orientation or gender identity; or socioeconomic, veteran or ability status—has the right to inclusion, respect, agency and voice in the Duke community.  Further, all members of the University community have a responsibility to uphold these values and actively foster full participation in university life."

It is my goal for our learning environment to facilitate learning and intellectual development for everyone. To help accomplish this:
  
  - If you have a name and/or set of pronouns that differ from those that appear in your official Duke records, please let me know.
  - We are constantly learning more about diverse perspectives and identities. If something occurred in class that made you feel uncomfortable, please talk to me about it. 
  

### Academic integrity

Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, respect, and accountability. Citizens of this community commit to reflect upon and uphold these principles in all academic and nonacademic endeavors, and to protect and promote a culture of integrity.

Remember the Duke Community Standard that you have agreed to abide by:
  
To uphold the Duke Community Standard:
  
- I will not lie, cheat, or steal in my academic endeavors;
- I will conduct myself honorably in all my endeavors; and
- I will act if the Standard is compromised.

Cheating or plagiarism on assignments, lying about an illness or absence and other forms of academic dishonesty are a breach of trust with classmates and faculty, violate the <a href="https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard">Duke Community Standard</a>, and will not be tolerated. Such incidences will result in a 0 grade.  Additionally, there may be penalties to your final class grade along with being reported to the <a href="https://studentaffairs.duke.edu/conduct/undergraduate-disciplinary-system">Undergraduate Conduct Board</a> (undergraduates) or relevant Director of Graduate Studies (graduate students).

Please review the Academic Dishonesty policies <a href="https://studentaffairs.duke.edu/conduct/z-policies/academic-dishonesty">here</a>. 

- Much of the work assigned in class is collaborative. The final project must be completed independently. Team labs to be completed by groups. For other assignments, while you may talk about strategies for completing them with other students in the class, the work you submit must be your own individual work.

- Important note: do not share your course materials with other students after completion of this course. Doing so will be considered a violation of the Duke Community Standard.

**Referencing code:** The web contains an enormous volume of code that you may find useful. You are welcome to make use of any online resources (e.g. StackOverflow), but you must explicitly cite your sources. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. On the final project you may not directly share code with another student in this class, and on team labs you may not share code with another team in this class (you are welcome to discuss the problems together and ask for advice, but you may not send or make use of code from another team). 

---- 

## How to be successful in this class

1. Do not have your phone out, TV on, or 20 other tabs open while viewing online lectures—focus and take notes as though you were in a traditional classroom.
2. Complete the videos/readings at the recommended pace, and review them after the unit is over.
3. Be an active virtual participant during group work, office hours, and review sessions.
4. Ask questions - during office hours, on Piazza, or via email. Ask me, your TAs, and your classmates.
5. Do the problem sets - start early and make sure you attempt and understand all questions.
6. Start your final project early and allow adequate time to complete it.
7. Do not procrastinate - don’t let a unit go by with unanswered questions as it will just make the following unit’s material even more difficult to follow.

## Course structure

The course is divided into seven learning units. Within each unit a set of daily learning objectives and required and suggested readings, videos, etc. will be posted on the course website, with due dates for each graded assignment noted. 

Generally, the framework for each unit will be as follows:

1. Prior to the start of each day within a unit you are expected to familiarize yourselves with the learning objectives for the day, and then watch the day's videos and/or complete the readings.
2. You will complement your learning with:
    * Problem sets; some will be ungraded and have answers available in the back of the textbook, others will be turned in for points. Collaboration is welcome, but your write ups must be done individually and show your own work.
    * Collaborative group work, some of which may be done via (optional) live guided practice sessions, or as a class on Piazza.
    * Labs, some of which will be done in teams.
    * Data-science-in-action seminars, followed by reflections.
3. At the end of each unit you will wrap up the module with a performance assessment, done individually, which is meant to gauge your comprehension of the material.

In addition to the standard formats of the units, there will be (approximately) weekly “Data Science in Action” lectures, two individual midterms, a final exam, and a project. 

---- 

## Time details

### Work load

You are expected to put in about 18-20 hours of work per week, including the time spent viewing the video content and reading the required material. Some of you will do well with less time than this, and some of you will need more. Note that the less distracted you are, and the more engaged with the material, the less time it will take (i.e., if you watch tv and text while viewing the content it will take longer to learn it because you are using your time less efficiently).

### Synchronous activities

There are no required synchronous activities in the course (meaning at no point in the class will your grade depend on you being online with everyone else at the same time). However, students are encouraged to attend the interactive sessions offered for the course (schedule shown on course home page and Detailed Schedule page); recordings will also be made available. The exams will be scheduled to last no more than 2 hours and fall within a given 24 window, but can be started at any time during that window.

Live video/audio office hours open to the whole class, hosted via Zoom, will take place throughout the week with each member of the instruction team. Additional office hours may be scheduled depending on student request and content in a given week.

You may be invited to take part in additional synchronous social or educational events, but you will not be required to participate and these will not impact your grade.

"Data Science in Action" sessions may occur "live", but will also be recorded and made available online. 

Scheduling for group work on labs and data-science-in-action reflections will be coordinated within individual teams.

### Asynchronous activities

Asynchronous activities (i.e., those without designated meeting times) include viewing lectures, completing the suggested readings, working on assignments, and engaging on Piazza.

The "Detailed schedule" page of the course website includes a daily schedule of readings/videos/work and due dates for all assignments. It is expected that you will not lag behind this daily schedule, so as to be able to complete individual assignments, contribute to team labs, and participate fully in discussions.

---- 

## Communication and feedback

### Communication

Any non-personal questions related to the material covered in class, problem sets, labs, project, etc. should be posted on Piazza. Before posting a new question please make sure to check if your question has already been answered, and answer others’ questions!

I will respond to Piazza posts directed to me and individual emails/messages sent between Monday and Thursday within 24 hours. For example, an email sent at 8 PM on Thursday will receive a reply no later than 8 PM on Friday; an email sent at noon on Saturday will receive a reply by the end of Monday. My response time will usually be faster. However, know that the window is up to 24 hours and a reply is not guaranteed on the weekends—meaning that it is important not to procrastinate on big assignments! If you ask a question an hour before something is due, you may not receive an answer before the assignment submission deadline.

### Feedback

Problem/lab solutions will be available after everyone has submitted the assignment. Graded problem sets and labs will be returned no later than 48 hours after the assignment due date. Weekly grades for Piazza participation (Monday through Sunday) will be provided no later than the following Wednesday each week.

Students will be required to schedule a 1-1 meeting with me for a point of their choosing in the semester. During this meeting, I will provide feedback on their submissions/participation thus far and discuss any topics/concerns/questions the student has. Please feel free to also request additional meetings, and/or come to my office hours!

### Piazza

A typical week on Piazza will include discussion content and/or polls posted by the instruction team, questions posed by students, and content posted by both students and the instruction team. To get the most out of this course, plan to log into Piazza and engage with your peers/instructors at least two to three times per week. 

Piazza is so heavily emphasized in this course for three primary reasons: 
1. Discussion provides continual opportunities to reflect, recall, and apply new knowledge.
2. You will have a chance to interact with each other and us, and build relationships.
3. We as your instruction team will use your questions and feedback to direct what content we provide/create.

To emphasize the importance of online participation, the quality of your participation will be reflected in your final grade in the course (see "Participation" section, below).

### Data science in action

We will have (approximately) weekly invited speakers in marine/environmental science talk about how they use data and information, the goal being to expose students to real life examples of statistical thinking. Later follow up interactions with students will occur on Piazza. Reflections on these seminars will contribute to your participation grade.

---- 

## Grading

*Grade breakdown:*

| Assignment type | Share of final grade|
| ------------- | ------------- |
| Participation | 15% |
| Problem sets | 15% |
| Labs | 15% |
| Project | 20% |
| Midterm 1 | 10% |
| Midterm 2 | 10% |
| Final | 15% |

*Curving:*
Grades may be curved at the end of the semester. Cumulative numerical averages of 90 - 100 are guaranteed at least an A-, 80 - 89 at least a B-, and 70 - 79 at least a C-, however the exact ranges for letter grades will be determined after the final exam. The more evidence there is that the class has mastered the material, the more generous the curve will be.

*Dropping scores:*
The lowest score will be dropped from each of the following categories: Problem sets, Labs, Data-science-in-action reflections, Performance assessments.

*Late work policy:*
There will be no late work accepted. The reason for this strict late work policy is so that solutions to problem sets can be released quickly for feedback to the rest of the class, and to emphasize the importance of following the pace of the course.

*Regrade requests:*
Regrade requests must be made within 48 hours of when the assignment is returned, and must be submitted to me in writing. These will be honored if points were tallied incorrectly, or if you feel your answer is correct but it was marked wrong. No regrade will be made to alter the number of points deducted for a mistake. There will be no grade changes after the final exam.

---- 

## Details about course components

Participation, problem sets, labs, project, midterms, finals... what are all of these things and why are you doing them!? Read on to find out.

### Participation

*Grade breakdown:*
1/3 completion of data science in action reflections.
1/3 completion of performance assessments.
1/3 activity on Piazza.

*Data science in action reflections (DSA):*

Participation grades in this category require you to reflect on the data science in action seminar. This reflection can take many forms: you can create a video, write a short essay, interact with the speaker, and/or synthesize what you heard with other work or areas of interest to you. You may complete these reflections in teams or groups of your choosing, or individually; check each assignment for more details.

*Performance assessments (PA):*
The objective of PAs is to evaluate your mastery of the material by the end of a unit and give you instant feedback on your performance. The format is 10 multiple choice questions. The assessments will be taken individually on Sakai. I suggest not using notes/books/videos while you take this, and using it as an honest test of your mastery of the past unit. 

You may miss one each of the DSAs and PAs without it impacting your grade. Your score on DSAs and PAs is based on completion; you may also resubmit them as many times as you would like up to the due date/time.

*Activity on Piazza:*
This component of your grade is based upon the content, depth and quality of your contributions to Piazza questions/discussions using the standards found within the grading rubric (see the rubric on Sakai under Resources). Sometimes the instruction team will create posts asking you to reflect on a Coursera lecture from that day, an exercise or topic from the textbook, or a news article. Participating consistently with thoughtful answers early in the week, and responding to and engaging in discussion with your peers will have positive effects on your overall grade. For grading purposes, each week runs Monday through Sunday. Your lowest Piazza activity grade will be dropped.

### Problem sets (PS)

These will be assigned (approximately) weekly on the course webpage. Each assignment will have problems to be turned in for grading, and practice problems from the OpenIntro book. You do not need to turn in the practice problems, and the solutions can be found in the back of the book.

The objective of the problem sets is to help you develop a more in-depth understanding of the material and help you prepare for exams and project. Grading will be based on completeness as well as accuracy. In order to receive credit you must show all your work.

*Lowest score will be dropped.*

You are welcomed, and encouraged, to work with each other on the problems, but you must turn in your own work. If you copy someone else’s work, both parties will receive a 0 for the problem set grade as well as being reported to the Office of Student Conduct. Submitted work will be checked for instances of plagiarism prior to being graded.

### Labs

The objective of the labs is to give you hands on experience with data analysis using modern statistical software. The labs will also provide you with tools that you will need to complete the project successfully. We will use a statistical analysis package called RStudio, which is a front end for the R statistical language.

Some labs will be done in teams. The TAs will host "live" lab meetings twice per week (recorded for those unable to attend), with additional help available in office hours. The TAs will also provide example content and resources on successful programming.

*Lowest score will be dropped.*

### Project

The project objective is to give you independent applied research experience using real data and statistical methods. For a parameter of interest to you, you will describe the relevant data, conduct an analysis, and summarize your findings in a written, fully reproducible, data analysis report. You will also upload a short video presentation in which you share your work with your peers. Students will view and engage with a subset of their peers’ projects, and respond to questions from those who viewed their presentation in the "project reflections" component of the assignment.

* Project proposal: 2/10 of overall project grade
* Project write-up/presentation: 7/10 of overall project grade
* Project reflections: 1/10 of overall project grade

You must score at least 30% of the points on each of the three project related submissions in order to pass this class.

### Exams

There will be two midterms and one final in this class. You will take the exams on Sakai. You may start the exam at any point during the specified 24 hour window; once you begin the exam you will have two hours in which to complete it. You can’t pass the class if you do not take the final exam.

Midterm 1 date: Thursday, May 28
Midterm 2 date: Thursday, June 11
Final date: Thursday, June 25

The midterm and final will be open course materials, but NOT open internet or open communication. That is, you can look at your OpenIntro book, notes, problem set keys, etc, but you cannot use google, ask your roommate for help, or post the exam question on StackExchange. Students will sign an honors statement attesting that they will not share work or solutions with fellow students, nor seek out any assistance with test content either online or in person. 

A common question is: What do I do if something goes wrong after I begin the exam? Monday through Thursday there is 24 hour support from the OIT service desk; Fridays 12am - 5pm; and Sundays 3pm - 12am. The phone number is (919) 684-2200. Obtain a ticket if Sakai crashes or the internet goes out in the middle of your exam, and contact me regarding how to proceed.

---- 

## Students with disabilities

Students with disabilities who believe they may need accommodations in this class are encouraged to contact the Student Disability Access Office at (919) 668-1267 as soon as possible to better ensure that such accommodations can be made.

## Excused absences

Students who miss graded work due to a scheduled varsity trip, religious holiday or short-term illness should fill out an online NOVAP, RHoliday or short-term illness form respectively. If you cannot complete an assignment on the due date due to a reported short-term illness, you have until noon the following day to complete it at no penalty. Then the regular late work policy will kick in. Those with a personal emergency or bereavement should seek a Dean’s Excuse: Check with your academic dean for details.

## Making up assignments

There will be no make-up for data-science-in-action reflections or performance assessments, labs, problem sets, project, or final exam. If a midterm exam must be missed, absence must be officially excused in advance, in which case the missing exam score will be imputed using the final exam score. This policy only applies to the midterms. All other missed assessments will receive a grade of 0. The final exam must be taken within the stated window. You must take the final exam and turn in all components of the project in order to pass this course.

Recall that to mitigate the impact of a 0 due to an unexpected missed assignment, the lowest grade from each of the following categories will be dropped: Problem sets, Labs, Data-science-in-action reflections, and Performance assessments.

## Additional information

*The Academic Resource Center (ARC):*
The Academic Resource Center (ARC) offers free services to all students during their undergraduate careers at Duke.  Services include Learning Consultations, Peer Tutoring and Study Groups, ADHD/LD Coaching, Outreach Workshops, and more. Because learning is a process unique to every individual, we work with each student to discover and develop their own academic strategy for success at Duke. Contact the ARC to schedule an appointment. Undergraduates in any year, studying any discipline can benefit!  
Location: 211 Academic Advising Center Building, East Campus – behind Marketplace
arc.duke.edu - theARC@duke.edu - 919-684-5917

*Emergency Notification:*
In an emergency, there are several ways that the University will contact you. Two are detailed below.  Campus emergency procedures are described here: http://emergency.duke.edu
1. Text Messaging: An alert message may be sent to the mobile devices of Duke community members who register for a new text messaging system. Sign up for DukeALERT text messages or learn more about text messaging at Duke.
2. LiveSafe Mobile App: Notifications may be sent through the LiveSafe Mobile app to notify members of the Duke community of emergency situations. The free mobile app, available through the Apple App Store and Android App Store, offers real-time, two-way communication between Duke community members and the Duke University Police Department.


